---
version: '2'
services:
  redis:
    image: redis:3.2
    ports:
      - 6379:6379

  mariadb:
    image: mariadb:10.3.7
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
